backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "project" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Project" # Used in the UI, ie.: "New Post"
    folder: "site/content/project" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    preview: false
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - label: Videos
        name: videos
        widget: list
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - {label: Description, name: desc, widget: text, required: false}
          - {label: YouTube ID, name: id, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: Photo Gallery
        name: photos
        widget: object
        required: false
        fields: 
          - {label: "Heading", name: "heading", widget: "string", required: false}
          - label: Images
            name: items
            widget: list
            fields:
              - {label: Image, name: image, widget: image, required: false}
              - {label: Caption, name: caption, widget: text, required: false}
  - name: "pages"
    label: "Pages"
    preview: false
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string, required: false}
          - {label: Image, name: image, widget: image, required: false}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Projects", name: projects, widget: list, fields: [
              {label: "Heading", name: "title", widget: "string"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "About", name: "about", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image, required: false}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/services/_index.md"
        label: "Services Page"
        name: "services"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image, required: false}
          - {label: Description, name: description, widget: string, required: false}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image, required: false}
          - label: Blurbs
            name: about
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image, required: false}
          - {label: Body, name: body, widget: markdown}
